export const ADD_FROM_API = 'ADD_FROM_API'
export const INCREMENT_INDEX = 'INCREMENT_INDEX'
export const ADD_ALL_FROM_API = 'ADD_ALL_FROM_API'

export const REFRESH_PEOPLE_DATA = 'REFRESH_PEOPLE_DATA'
export const ADD_PERSON_TO_USER_DATA = 'ADD_PERSON_TO_USER_DATA'
export const INCREMENT_LASTID = 'INCREMENT_LASTID'
